from transformers import T5ForConditionalGeneration, T5Tokenizer
import os

# --- Global Constant ---
MODEL_PATH = "./results-biolaysumm/final_model"
TASK_PREFIX = "Summarize this radiology report in plain language: "

def generate_summary(model, tokenizer, report_text: str):
    """
    Generates a layman summary for a given radiology report.
    """
    input_text = TASK_PREFIX + report_text
    input_ids = tokenizer(input_text, return_tensors="pt").input_ids
    
    # Move to GPU if available (optional but recommended)
    if model.device.type == 'cuda':
        input_ids = input_ids.to(model.device)

    # Generate the summary
    outputs = model.generate(
        input_ids,
        max_length=150,
        num_beams=4,
        early_stopping=True
    )
    
    summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return summary

def main():
    if not os.path.exists(MODEL_PATH):
        print(f"Error: Trained model not found at {MODEL_PATH}.")
        print("Please run 'python train.py' first.")
        return

    # 1. Load the fine-tuned model and tokenizer
    print(f"Loading model from {MODEL_PATH}...")
    tokenizer = T5Tokenizer.from_pretrained(MODEL_PATH)
    model = T5ForConditionalGeneration.from_pretrained(MODEL_PATH)

    # 2. Example Report
    example_report = (
        "FINDINGS: There is a 3 cm area of ill-defined enhancement in the right "
        "upper lobe, concerning for malignancy. No evidence of metastasis. "
        "IMPRESSION: Highly suspicious for primary lung carcinoma (likely adenocarcinoma). "
        "Recommend biopsy for definitive diagnosis."
    )
    
    # 3. Generate and Print Summary
    summary = generate_summary(model, tokenizer, example_report)
    
    print("-" * 50)
    print("Radiology Report:")
    print(example_report)
    print("-" * 50)
    print("Layman Summary (Generated by Model):")
    print(summary)
    print("-" * 50)

if __name__ == "__main__":
    main()